const BusinessCode = {
  LOGIN_SUCCESS: 'L001',
  LOGIN_FAILED: 'L002',
  DELETE_VIDEO_SUCCESS: 'B003',
  INFO_SUCCESS: 'MI001',
  INFO_FAILED: 'MI002',
  GROUP_SELECT_SUCCESS: 'CL001',
  GROUP_SELECT_FAILED: 'CL002',
  GROUP_INSERT_SUCCESS: 'CC001',
  GROUP_INSERT_FAILED: 'CC002',
};

Object.freeze(BusinessCode);

export default BusinessCode;
