const BusinessCode = {
  LOGIN_SUCCESS: 'L001',
  LOGIN_FAILED: 'L002',
  DELETE_VIDEO_SUCCESS: 'B003',
  INFO_SUCCESS: 'MI001',
  INFO_FAILED: 'MI002',
  GROUP_SELECT_SUCCESS: 'CL001',
  GROUP_SELECT_FAILED: 'CL002',
  GROUP_INVITE_SUCCESS: 'IV001',
  GROUP_INVITE_FAILED: 'IV002',
  GROUP_MEMBER_SELECT_SUCCESS: 'ML001',
  GROUP_MEMBER_SELECT_FAILED: 'ML002',
  GROUP_MEMBER_DELETE_SUCCESS: 'LV001',
  GROUP_MEMBER_DELETE_FAILED: 'LV002',
  GROUP_MEMBER_SEARCH_SUCCESS: 'MS001',
  GROUP_MEMBER_SEARCH_FAILED: 'MS002',
  GROUP_INSERT_SUCCESS: 'CC001',
  GROUP_INSERT_FAILED: 'CC002',
};

Object.freeze(BusinessCode);

export default BusinessCode;
