name: Docker Image로 만들어서 배포하기

on:
  push:
    branches:
      - sprint-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t vidigummy/longs-fe:${{ github.run_id }} -t vidigummy/longs-fe:latest -f Dockerfile .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push vidigummy/longs-fe:${{ github.run_id }}

     - name: Push Docker image latest
      run: docker push vidigummy/longs-fe:latest
      
  deploy:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: excute docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          password: ${{ secrets.GCE_ROOT_PW }}
          port: 22
          script: |
            cd /app/longs-env/env-dev
            docker compose up -d
